const $ = (s,c=document)=>c.querySelector(s); const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const toast=(m,t='success',d='')=>window.appToast?.(m,t,d); const confirmAction=o=>window.appConfirm?.(o)??Promise.resolve(false); const escape=v=>window.appEscape?window.appEscape(v):String(v??'');
const doctorState={user:null,doctor:null,appointments:[],calendarDate:new Date(),selectedDate:null,current:null};
function money(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—';}
function dateOnly(v){return v?String(v).slice(0,10):'';} function localDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function dateBR(v){const r=dateOnly(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(r))return'—';const[y,m,d]=r.split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('pt-BR');}
function dateTime(v){if(!v)return'—';const d=new Date(String(v).replace(' ','T'));return Number.isNaN(d.getTime())?String(v):d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});} function time(v){return v?String(v).slice(0,5):'—';}
function pretty(v){return String(v||'Não informada').replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());} function initial(v){return String(v||'M').trim().charAt(0).toUpperCase();}
function statusBadge(s){const c=s==='realizada'||s==='confirmada'?'success':s==='cancelada'?'danger':'warning';const l={agendada:'Agendada',confirmada:'Confirmada',realizada:'Realizada',cancelada:'Cancelada'}[s]||s;return`<span class="badge ${c}">${l}</span>`;} function payBadge(s){return`<span class="badge ${s==='pago'?'success':'warning'}">${s==='pago'?'Pago':'Pendente'}</span>`;}
async function api(url,opt={}){const r=await fetch(url,{cache:'no-store',...opt,headers:{...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})}});let d={};try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d.erro||'Não foi possível concluir a operação.');return d;}
async function ensureDoctor(){try{const d=await api('/api/sessao');if(!d.logado||d.usuario.tipo!=='medico')throw 0;doctorState.user=d.usuario;return true}catch(_){location.href='login.html';return false}}
function openModal(id){$(`#${id}`)?.classList.add('open');window.refreshIcons?.();}function closeModal(id){$(`#${id}`)?.classList.remove('open');}$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));$$('.app-modal-overlay').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
function setSection(name){$$('.doctor-menu-item').forEach(b=>b.classList.toggle('ativo',b.dataset.section===name));$$('.doctor-section').forEach(s=>s.classList.toggle('ativo',s.id===`section-${name}`));const t={dashboard:['Visão geral','Sua agenda e atendimentos.'],agenda:['Minha agenda','Consultas relacionadas ao seu perfil.'],atendimento:['Atendimento','Consultas de hoje.'],historico:['Histórico','Consultas finalizadas.'],perfil:['Meu perfil','Dados profissionais.']}[name];$('#page-title').textContent=t[0];$('#page-subtitle').textContent=t[1];if(name==='perfil')loadProfile();if(name==='historico')renderHistory();if(name==='atendimento')renderAttendance();}
$$('.doctor-menu-item').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.section)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>setSection(b.dataset.go)));

async function loadPanel(){try{const d=await api('/api/meus-agendamentos');doctorState.doctor=d.medico;doctorState.appointments=Array.isArray(d.agendamentos)?d.agendamentos:[];applyDoctorIdentity();renderDashboard();renderCalendar();renderAttendance();renderHistory();}catch(err){toast(err.message,'error')}}
function applyDoctorIdentity(){const d=doctorState.doctor;if(!d)return;$('#doctor-sidebar-name').textContent=d.nome;$('#doctor-sidebar-specialty').textContent=pretty(d.especialidade);$('#doctor-welcome').textContent=`Olá, ${d.nome}`;const av=$('#doctor-sidebar-avatar');av.innerHTML=d.foto?`<img src="${d.foto}" alt="Foto">`:escape(initial(d.nome));}
function upcoming(a){const now=new Date(),dd=dateOnly(a.data),tt=time(a.horario);if(['realizada','cancelada'].includes(a.status))return false;const x=new Date(`${dd}T${tt}:00`);return !Number.isNaN(x.getTime())&&x>=now;}
function compare(a,b){return `${dateOnly(a.data)} ${time(a.horario)}`.localeCompare(`${dateOnly(b.data)} ${time(b.horario)}`);}
function empty(icon,title,text){return`<div class="empty-state"><i data-lucide="${icon}"></i><strong>${escape(title)}</strong><span>${escape(text)}</span></div>`;}
function agendaItem(a){return`<button class="agenda-item" data-open-consult="${a.id}" type="button" style="width:100%;border:0;background:transparent;color:inherit;text-align:left;cursor:pointer"><strong>${time(a.horario)}</strong><div><span class="cell-primary">${escape(a.paciente)}</span><span class="cell-secondary">${dateBR(a.data)} • ${escape(a.motivo_consulta||'Sem motivo informado')}</span></div><div>${statusBadge(a.status)}</div><div>${payBadge(a.pagamento_status)}</div></button>`;}
function wireConsultButtons(root=document){$$('[data-open-consult]',root).forEach(b=>b.addEventListener('click',()=>openConsult(b.dataset.openConsult)));}
function renderDashboard(){const today=localDate(new Date()),todays=doctorState.appointments.filter(a=>dateOnly(a.data)===today&&a.status!=='cancelada'),next=doctorState.appointments.filter(upcoming).sort(compare),done=doctorState.appointments.filter(a=>a.status==='realizada').length;$('#doc-today').textContent=todays.length;$('#doc-next').textContent=next[0]?`${time(next[0].horario)} • ${next[0].paciente}`:'Nenhuma';$('#doc-done').textContent=done;$('#doc-patients').textContent=new Set(todays.map(a=>a.paciente_id||a.email)).size;const box=$('#doctor-next-list');box.innerHTML=next.length?next.slice(0,6).map(agendaItem).join(''):empty('calendar-x','Nenhuma consulta próxima','Sua agenda futura está livre.');wireConsultButtons(box);window.refreshIcons?.();}

function renderCalendar(){const y=doctorState.calendarDate.getFullYear(),m=doctorState.calendarDate.getMonth(),names=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];$('#doc-calendar-title').textContent=`${names[m]} ${y}`;let html=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(x=>`<div class="calendar-weekday">${x}</div>`).join('');const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++)html+='<div class="calendar-cell muted"></div>';for(let day=1;day<=days;day++){const date=localDate(new Date(y,m,day)),items=doctorState.appointments.filter(a=>dateOnly(a.data)===date);html+=`<button class="calendar-cell ${date===localDate(new Date())?'today':''}" data-doc-date="${date}" type="button"><span class="calendar-number">${day}</span>${items.length?`<span class="calendar-count">${items.length} ${items.length===1?'consulta':'consultas'}</span>`:''}</button>`;}$('#doc-calendar').innerHTML=html;$$('[data-doc-date]').forEach(b=>b.addEventListener('click',()=>showDay(b.dataset.docDate)));window.refreshIcons?.();if(doctorState.selectedDate)showDay(doctorState.selectedDate,false);}
function showDay(date,scroll=true){doctorState.selectedDate=date;const items=doctorState.appointments.filter(a=>dateOnly(a.data)===date).sort(compare),d=new Date(`${date}T12:00:00`);$('#doc-selected-title').textContent=d.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'});$('#doc-selected-subtitle').textContent=`${items.length} ${items.length===1?'consulta':'consultas'}`;const box=$('#doc-selected-list');box.innerHTML=items.length?items.map(agendaItem).join(''):empty('calendar-x','Dia livre','Nenhuma consulta nesta data.');$('#doc-selected-day').style.display='block';wireConsultButtons(box);if(scroll)$('#doc-selected-day').scrollIntoView({behavior:'smooth',block:'nearest'});window.refreshIcons?.();}
$('#doc-prev').addEventListener('click',()=>{doctorState.calendarDate.setMonth(doctorState.calendarDate.getMonth()-1);doctorState.selectedDate=null;$('#doc-selected-day').style.display='none';renderCalendar()});$('#doc-next-btn').addEventListener('click',()=>{doctorState.calendarDate.setMonth(doctorState.calendarDate.getMonth()+1);doctorState.selectedDate=null;$('#doc-selected-day').style.display='none';renderCalendar()});$('#doc-today-btn').addEventListener('click',()=>{doctorState.calendarDate=new Date();showDay(localDate(new Date()));renderCalendar()});
function renderAttendance(){const today=localDate(new Date()),items=doctorState.appointments.filter(a=>dateOnly(a.data)===today&&!['realizada','cancelada'].includes(a.status)).sort(compare),box=$('#doctor-attendance-list');box.innerHTML=items.length?items.map(agendaItem).join(''):empty('clipboard-check','Nenhum atendimento pendente','Não há consultas de hoje aguardando atendimento.');wireConsultButtons(box);window.refreshIcons?.();}
function renderHistory(){const q=($('#doctor-history-search')?.value||'').trim().toLowerCase(),rows=doctorState.appointments.filter(a=>a.status==='realizada'&&(!q||String(a.paciente).toLowerCase().includes(q))).sort((a,b)=>compare(b,a)),body=$('#doctor-history-table');body.innerHTML=rows.length?rows.map(a=>`<tr class="clickable" data-open-consult="${a.id}"><td><span class="cell-primary">${escape(a.paciente)}</span><span class="cell-secondary">${escape(a.email)}</span></td><td>${dateBR(a.data)}<span class="cell-secondary">${time(a.horario)}</span></td><td>${escape(pretty(a.especialidade))}</td><td>${a.retorno?(a.data_retorno?dateBR(a.data_retorno):'Sim'):'Não'}</td><td><button class="icon-button"><i data-lucide="chevron-right"></i></button></td></tr>`).join(''):`<tr><td colspan="5">${empty('history','Nenhum registro encontrado','Consultas finalizadas aparecerão aqui.')}</td></tr>`;wireConsultButtons(body);window.refreshIcons?.();}
$('#doctor-history-search').addEventListener('input',renderHistory);

function ageFromBirth(v){const raw=dateOnly(v);if(!raw)return'Não informada';const b=new Date(`${raw}T12:00:00`),n=new Date();let a=n.getFullYear()-b.getFullYear();const md=n.getMonth()-b.getMonth();if(md<0||(md===0&&n.getDate()<b.getDate()))a--;return a>=0?`${a} anos`:'Não informada';}
async function openConsult(id){try{const [{consulta:a},history]=await Promise.all([api(`/api/meus-agendamentos/${id}`),api(`/api/meus-agendamentos/${id}/historico-paciente`)]);doctorState.current=a;$('#consult-id').value=a.id;$('#consult-title').textContent=a.paciente;$('#consult-subtitle').textContent=`${dateBR(a.data)} às ${time(a.horario)} • ${statusLabel(a.status)}`;$('#consult-summary').innerHTML=[['Paciente',a.paciente],['Idade',ageFromBirth(a.paciente_data_nascimento)],['Data',dateBR(a.data)],['Horário',time(a.horario)],['Motivo',a.motivo_consulta||'Não informado'],['Status',statusBadge(a.status),true],['Pagamento',payBadge(a.pagamento_status),true],['Valor',money(a.valor_consulta)]].map(([l,v,h])=>`<div class="detail-row ${l==='Motivo'?'full':''}"><span>${l}</span>${l==='Motivo'?`<p>${escape(v)}</p>`:`<strong>${h?v:escape(v)}</strong>`}</div>`).join('');$('#consult-diagnosis').value=a.diagnostico||'';$('#consult-prescription').value=a.receita||'';$('#consult-notes').value=a.observacoes||'';$('#consult-return').value=Number(a.retorno)?'1':'0';$('#consult-return-date').value=dateOnly(a.data_retorno);updateReturnDateState();const locked=['realizada','cancelada'].includes(a.status);['#consult-diagnosis','#consult-prescription','#consult-notes','#consult-return','#consult-return-date'].forEach(s=>$(s).disabled=locked);$('#save-consult').hidden=locked;$('#finish-consult').hidden=locked;$('#print-prescription').hidden=!a.receita&&!$('#consult-prescription').value;$('#patient-history-mini').innerHTML=history.length?history.map(h=>`<div style="padding:10px 0;border-bottom:1px solid var(--border)"><strong>${dateBR(h.data)} • ${escape(pretty(h.especialidade))}</strong><span class="cell-secondary">${escape(h.diagnostico||'Sem diagnóstico informado')}</span></div>`).join(''):empty('history','Sem histórico anterior','Nenhuma consulta anterior deste paciente com você.');openModal('doctor-appointment-modal');window.refreshIcons?.();}catch(err){toast(err.message,'error')}}
function statusLabel(s){return{agendada:'Agendada',confirmada:'Confirmada',realizada:'Realizada',cancelada:'Cancelada'}[s]||s;}
function consultPayload(){return{diagnostico:$('#consult-diagnosis').value.trim(),receita:$('#consult-prescription').value.trim(),observacoes:$('#consult-notes').value.trim(),retorno:$('#consult-return').value==='1',data_retorno:$('#consult-return').value==='1'?$('#consult-return-date').value:null};}
function updateReturnDateState(){$('#consult-return-date').disabled=$('#consult-return').disabled||$('#consult-return').value!=='1';if($('#consult-return').value!=='1')$('#consult-return-date').value='';}
$('#consult-return').addEventListener('change',updateReturnDateState);
$('#save-consult').addEventListener('click',async()=>{const id=$('#consult-id').value,p=consultPayload();if(p.retorno&&!p.data_retorno)return toast('Informe a data do retorno.','warning');try{const r=await api(`/api/meus-agendamentos/${id}/salvar`,{method:'PUT',body:JSON.stringify(p)});toast(r.mensagem);await loadPanel();}catch(err){toast(err.message,'error')}});
$('#finish-consult').addEventListener('click',async()=>{const id=$('#consult-id').value,p=consultPayload();if(p.retorno&&!p.data_retorno)return toast('Informe a data do retorno.','warning');const ok=await confirmAction({title:'Finalizar atendimento?',message:'Depois de finalizar, o registro clínico ficará como consulta realizada.',confirmText:'Finalizar atendimento'});if(!ok)return;try{const r=await api(`/api/meus-agendamentos/${id}/realizar`,{method:'PUT',body:JSON.stringify(p)});toast(r.mensagem);closeModal('doctor-appointment-modal');await loadPanel();window.loadNotifications?.();}catch(err){toast(err.message,'error')}});
$('#print-prescription').addEventListener('click',printPrescription);
async function printPrescription(){const a=doctorState.current,prescription=$('#consult-prescription').value.trim()||a?.receita;if(!a||!prescription)return toast('Não há receita preenchida para imprimir.','warning');let clinic={};try{clinic=await api('/api/configuracoes/publicas')}catch(_){}const w=window.open('','_blank','width=850,height=700');if(!w)return toast('O navegador bloqueou a janela de impressão.','warning');w.document.write(`<!doctype html><html><head><title>Receita - ${escape(a.paciente)}</title><style>body{font-family:Arial,sans-serif;color:#111;padding:48px;line-height:1.55}.head{border-bottom:2px solid #0f766e;padding-bottom:18px;margin-bottom:26px}.brand{font-size:24px;font-weight:700}.meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:30px}.label{font-size:11px;text-transform:uppercase;color:#666}.value{font-weight:600}.rx{white-space:pre-wrap;font-size:16px;min-height:250px}.sign{margin-top:70px;border-top:1px solid #999;width:300px;padding-top:8px}</style></head><body><div class="head"><div class="brand">${escape(clinic.nome_clinica||'Clínica Vida+')}</div><div>${escape(clinic.endereco||'')} ${clinic.telefone?'• '+escape(clinic.telefone):''}</div></div><div class="meta"><div><div class="label">Paciente</div><div class="value">${escape(a.paciente)}</div></div><div><div class="label">Data</div><div class="value">${dateBR(a.data)}</div></div><div><div class="label">Médico</div><div class="value">${escape(doctorState.doctor.nome)}</div></div><div><div class="label">CRM</div><div class="value">${escape(doctorState.doctor.crm||'Não informado')}</div></div></div><h2>PRESCRIÇÃO</h2><div class="rx">${escape(prescription)}</div><div class="sign">${escape(doctorState.doctor.nome)}<br>${escape(doctorState.doctor.crm||'')}</div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close();}

async function loadProfile(){try{const d=await api('/api/medico/perfil');doctorState.doctor={...doctorState.doctor,...d};$('#doctor-profile-name').textContent=d.nome;$('#doctor-profile-role').textContent=pretty(d.especialidade);$('#profile-name').textContent=d.nome||'—';$('#profile-cpf').textContent=d.cpf||'Não informado';$('#profile-phone').textContent=d.telefone||'Não informado';$('#profile-email').textContent=d.email||'—';$('#profile-crm').textContent=d.crm||'Não informado';$('#profile-specialty').textContent=pretty(d.especialidade);$('#profile-price').textContent=money(d.valor_consulta);$('#profile-status').innerHTML=`<span class="badge ${Number(d.ativo)?'success':'danger'}">${Number(d.ativo)?'Ativo':'Inativo'}</span>`;$('#profile-created').textContent=d.criado_em?dateBR(d.criado_em):'—';const photo=$('#doctor-profile-photo');photo.innerHTML=d.foto?`<img src="${d.foto}" alt="Foto de perfil">`:escape(initial(d.nome));applyDoctorIdentity();window.refreshIcons?.();}catch(err){toast(err.message,'error')}}
$('#doctor-photo-input').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(f.size>2*1024*1024){toast('A foto deve ter no máximo 2 MB.','warning');e.target.value='';return;}try{const data=await fileToDataUrl(f),r=await api('/api/medico/foto',{method:'PUT',body:JSON.stringify({foto:data})});toast(r.mensagem);await Promise.all([loadProfile(),loadPanel()]);}catch(err){toast(err.message,'error')}finally{e.target.value=''}});
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
$('#logout').addEventListener('click',async()=>{try{await api('/api/logout',{method:'POST'})}catch(_){}location.href='login.html'});

document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')loadPanel()});
(async function init(){if(!await ensureDoctor())return;await Promise.all([loadPanel(),loadProfile()]);document.querySelector('#page-loader')?.classList.add('hidden');setInterval(()=>{if(document.visibilityState==='visible')loadPanel()},20000);window.refreshIcons?.();})();
